### ISSUE TITLE
cortexstore.val() out of synch with cortexstore.map()

### ISSUE THREAD

**Issue by serle** [mquan/cortex#101]
After removing a value from an array (by resetting the whole array i.e. not using splice), I'm finding that if I use cortextstore.val() I get the right elements in the array, but when using cortexstore.map I get the same number of elements before the cortexstor.set operation.

Could this have to do with flushing the updates in the store?

**Comment by mquan** [comment]
I believe the problem here is also related to this explanation https://github.com/mquan/cortex/issues/100#issuecomment-153926683
