### ISSUE TITLE
Reference error after remove item from array using splice / destroy.

### ISSUE THREAD

**Issue by blackChef** [mquan/cortex#106]
Below is a simple app that create a list of 3 counters. Each counter item has a button which after clicked, remove that counter from list ( use `array.splice` or `arrayItem.destroy` ).
After remove first one, trying to increase second counter actually increase third one. After remove second counter, trying to increase third counter will get error: `Cannot read property 'getPath' of undefined`

    import React from 'react';
    import ReactDOM from 'react-dom';
    import Cortex from 'cortexjs';

    let Counter = React.createClass({
      add() {
        let { count } = this.props;
        count.set( count.val() + 1 );
      },

      render() {
        return (
          <span>
            <span>count: {this.props.count.val()}</span>
            <button onClick={this.add}>increase</button>
          </span>
        );
      },
    });

    let List = React.createClass({
      render() {
        let { list } = this.props;

        let counters = list.map(item => {
          let id = item.id.val();

          let removeItem = () => {
            // remove cirtain item from list
            // after remove, <Counter /> not work as expected
            let targetIndex = list.findIndex(item => item.id.val() == id);
            list.splice(targetIndex, 1);

            // got same error if use destory
            // item.destroy();
          };

          return (
            <div>
              <div>id: {id}</div>
              <Counter count={item.count}/>
              <button
                type="button"
                onClick={removeItem}
              >
                remove this counter
              </button>
            </div>
          );
        });

        return (
          <div>
            {counters}
          </div>
        );
      },
    });

    let App = React.createClass({
      componentWillMount() {
        let initialData = [
          { id: 0, count: 0 },
          { id: 1, count: 0 },
          { id: 2, count: 0 },
        ];

        let list = new Cortex(initialData, newlist => {
          this.setState({ list: newlist });
        });

        this.setState({ list });
      },

      render() {
        return (
          <List list={this.state.list}/>
        );
      },
    });

    ReactDOM.render(<App />, document.querySelector('.appContainer'));

**Comment by blackChef** [comment]
I think I found the problem.
Cortex use array element's index as `path`. After adding / removing element from array, element's index changes. However, if that element is a object, `path` for that object, and path for any nested element of that object wont update.

    let list = [
      { id: 0, count: 0, foo: { bar: { name: 'john' } } },
      { id: 1, count: 0, foo: { bar: { name: 'sam' } } },
    ];


    console.log( list[1].foo.bar.name.__path ) // [1, 'foo', 'bar', 'name']

    list.shift(); // remove first item

    console.log( list[0].foo.bar.name.__path ) // [1, 'foo', 'bar', 'name']

**Comment by mquan** [comment]
I think there's scoping issue with the way you define individual `removeItem`. Those method probably have references to the previous cortex object instead of the updated one. Define it on the List component instead (it accepts an id and invoke and pass it in from the children). When the list changes, cortex will rewrap entire list object and since it's a brand new object the path should be correct.

**Comment by blackChef** [comment]
No, it's not a scoping issue.
Please see this [example](http://codepen.io/chef/pen/RGVrVQ?editors=1010)
Click shift, then click setFirst, get error: `Cannot read property 'getPath' of undefined`.

**Comment by mquan** [comment]
@blackChef yes this is a bug with the rewrapping mechanism. In your example if you look at `list[0].__path` then it will report the right path after `shift`. However, that path change isn't propagated down to every children in the subtree. Thanks for debuggin it. Let me have a look at the code and figure out a solution.

**Comment by mquan** [comment]
Hi @blackChef Thanks for finding the problem. I fixed the issue and added more test cases to cover this bug. Please let me know if you find anything missing.
