### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by smhg** [mquan/cortex#108]
Hi! I wanted to report an issue and submit a failing test case for it.
But I tests aren't running for me. I followed these steps:

```bash
gulp
```
It performs `scripts` and `default` tasks, but it never exits. I have to use Ctrl+C to end.

```bash
gulp test
```
This finishes, but returns `No specs found`. I've tried running it in the project's root and test directories.

I'm on **node 6.11.0** and **npm 5.0.3**.
What am I missing?

**Comment by mquan** [comment]
@smhg I haven't tested the project with recent node and npm versions, my guess is the build tool needs to be updated. But if you run with node v4.3.0, you should be able to see tests running.

**Comment by smhg** [comment]
Thanks for the response.

I tried with node 4.3.0 (and 4.3.2, 4.8.3), but the results are the same. Maybe it's because I'm on Linux.

But just to make sure: are you able to `git clone` the project into a new directory, do `npm i` and run `node_modules/.bin/gulp` (and `node_modules/.bin/gulp test`)?
If this does work for you, I'll try to figure out the gulp config.

**Comment by mquan** [comment]
Yes that works for me, and I'm using node v8.0.0 and npm v5.0.3
