### ISSUE TITLE
Exposing diffs

### ISSUE THREAD

**Issue by mehdi-cit** [mquan/cortex#52]
Hello and thanks for the 'cortex'!
Would it be possible to expose the changes/updates that the state has undergone. For instance in the simple example, the 'on update' let's you update the props.
orderCortex.on("update", function(updatedOrder) {
  orderComponent.setProps({order: updatedOrder});
});
I think having a function to get the difference between formerOrder and the updatedOrder could be useful. For instance when some 'root component' needs to communicate the changes it has undergone to another 'root component'.

**Comment by mquan** [comment]
Sorry this is long overdue but this feature is finally available in this commit https://github.com/mquan/cortex/commit/4fcfc56f0d7674e3413a7914e7a1234af5517de8

Please check out the documentation in README
