### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by gbuszmicz** [mquan/cortex#61]
First of all let me tell you that cortex is great!
Is there a way to achieve server side rendering? I read the docs and the examples but I just can´t get it working properly without erros.
I can pass the state with JSON.stringify(new Cortex(data)), but i can´t figure out how to use cortex with React.renderToString(...) server side.
I think it would be very useful to have this functionality.

The only way I get this running is having different react components for server and client, which gives the warning in browser:
"
React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.
"
but works.

Thanks

**Comment by mquan** [comment]
I haven't tried server side rendering, do you have code sample?

**Comment by gbuszmicz** [comment]
This is how I get it working right now. I have 2 differents react components: one with cortex support (_EventList_) and the other with no cortex support (_EventList_NoCortex_)

&nbsp;

**EventList.js**         _// cortex component_
```javascript
module.exports = EventList = React.createClass({
	render: function() {
	    var content = this.props.events.map(function(event){
	      return (
	        <Event key={event._id.getValue()} event={event} /> // get _id value from cortex
	      )
	    });
	    return (
	      <ul className="events-loop">{content}</ul>
	    )
  }
});
```

&nbsp;

**EventList_NoCortex.js**        _// No cortex component_
```javascript
module.exports = EventListNoCortex = React.createClass({
	render: function() {
	    var content = this.props.events.map(function(event){
	      return (
	        <Event key={event._id} event={event} /> // no cortex here
	      )
	    });
	    return (
	      <ul className="events-loop">{content}</ul>
	    )
  }
});
```

The only difference between this components is the _.getValue()_ method.
I know I could just put all this in one single file and test for the function like this:
```javascript
if (typeof this.props.events.getValue == 'function') { ... }
```
but that is not important right now.

&nbsp;

**server.js**
```javascript
var EventListNoCortex = require('./EventList_NoCortex'); // no cortex component

var events = [
      {_id:54a1709c1111111111111111, name:'My first event'},
      {_id:54a1709c2222222222222222, name:'My second event'},
      {_id:54a1709c3333333333333333, name:'My last event'}
    ];

var markup = React.renderToString( // here is the problem, rendering server side
  EventListNoCortex({
    events: events
  })
);
return res.render('template', { // node + express + EJS template engine
	markup: markup,
	state: JSON.stringify(events)
});
```
If I try to React.renderToString the cortex component (_EventList.js_) instead the no cortex one I get this error
> error: uncaughtException: Object 54a1709c1111111111111111 has no method 'getValue'

&nbsp;

**template.html**     _// with EJS_
```javascript
<section id="react-app"><%- locals.markup %></div>
<script id="initial-state" type="application/json"><%- locals.state %></script>
<script src="/js/bundle.js"></script>
```

&nbsp;

**client.js**           _// with this file I build the **bundle.js** in template.html using browserify_
```javascript
var Cortex = require('cortexjs')
var EventList = require('./EventList'); // component with cortex
var initialState = JSON.parse(document.getElementById('initial-state').innerHTML); // take the initial state data from browser

var cortex = new Cortex(initialState); 

var eventList = React.render(
  <EventList events={cortex} />,
  	document.getElementById('react-app')
);

cortex.on('update', function(cortexUpdatedData) {
	eventList.setProps({events: cortexUpdatedData});
});
```

**Comment by mquan** [comment]
Check out this issue https://github.com/mquan/cortex/issues/8

**Comment by mquan** [comment]
What's the error when you call `React.renderToString` with cortex? Have you tried using cortex without adding the callback on the server?

**Comment by gbuszmicz** [comment]
Ok, so I removed the callback like you said and now is working the server side rendering.

**EventList.js**    _// this is the react component_
```javascript
module.exports = EventList = React.createClass({
    render: function() {
        var content = this.props.events.map(function(event){
          return (
            <Event key={event.getValue()._id} event={event} /> // Is this normal?
          )
        });
        return (
          <ul className="events-loop">{content}</ul>
        )
  }
});
```

**server.js**    _// this is the server part_
```javascript
var EventList = require('./EventList');
var events = [
      {_id:54a1709c1111111111111111, name:'My first event'},
      {_id:54a1709c2222222222222222, name:'My second event'},
      {_id:54a1709c3333333333333333, name:'My last event'}
    ];

var cortex = new Cortex(events);
var markup = React.renderToString(
  EventList({
    events: cortex
  })
);
return res.render('template', {
    markup: markup,
    state: JSON.stringify(events)  // I`m using the stringify with NO cortex
});
```

**client.js**    _// this is the bundle.js in the template_
```javascript
var EventList = require('./EventList');
var initialState = JSON.parse(document.getElementById('initial-state').innerHTML); // take the initial state data from browser

var cortex = new Cortex(initialState); 
var eventList = React.render(
  <EventList events={cortex} />,
    document.getElementById('react-app')
);

cortex.on('update', function(cortexUpdatedData) {
    eventList.setProps({events: cortexUpdatedData});
});
```

The only weird thing is that in the react component I have to access the values like this:
```javascript
event.getValue()._id     // result: 54a1709c1111111111111111
```
instead of
```javascript
event._id.getValue()     // result: error: uncaughtException: Cannot call method 'getValue' of undefined
```

Is this behavior correct?

**Comment by mquan** [comment]
No, cortex doesn't work like that. Check what `initialState` on client side is.

Also, just debug on server first, your `EventList` uses `event.getValue()._id`, that is wrong, the `_id` is probably not the value that you want. Just get server side to render correctly w/ `event._id.getValue()`, try  testing with `name` key, does `event.getValue().name` work?

**Comment by gbuszmicz** [comment]
Ok, so after hours of testing now is working perfectly!

It was all my fault. But I will explain my error, may be can help others.

For my example here I was using this model:


```javascript
var events = [
      {_id:'54a1709c1111111111111111', name:'My first event'},
      {_id:'54a1709c2222222222222222', name:'My second event'},
      {_id:'54a1709c3333333333333333', name:'My last event'}
    ];
```


But in production I was actually getting this from a mongodb database, with mongoose.
http://mongoosejs.com/

The result of the query is a mongoose document and that is why cortex was running in a funny way, like this:


```javascript
event.getValue()._id    // 54a1709c1111111111111111
```
```javascript
event.getValue().name    // My first event
```


The solution was just getting a JS object from the query instead of a mongoose doc.
http://mongoosejs.com/docs/api.html#query_Query-lean

Adding a `.lean()` in the mongoose query get cortex working just fine!

I really appreciate your help. Thank you!
Cortex is great!
