### ISSUE TITLE
Demos don't work?

### ISSUE THREAD

**Issue by Trevoke** [mquan/cortex#63]
React not available in either of them.

**Comment by mquan** [comment]
React is loaded from a cdn https://github.com/mquan/cortex/blob/master/examples/skyline/index.html#L5

**Comment by Trevoke** [comment]
![screen shot 2015-02-07 at 10 33 54 am](https://cloud.githubusercontent.com/assets/67913/6092627/e292acbc-aeb4-11e4-96bd-8e45f6fe9098.png)

**Comment by mquan** [comment]
This demo works fine for me http://mquan.github.io/cortex/examples/skyline/

You seem to have an old version of the demo. The current demos use react 0.12

**Comment by mquan** [comment]
Sorry, the demo on github pages is still on 0.8.0. I'll update it immediately but the current ones should work. I just loaded from my mobile safari. You may want to check your browser security settings or try it on a different browser

**Comment by mquan** [comment]
All fixed. I updated the README to point to https github page. Thanks
