### ISSUE TITLE
Confusion regarding on("update") and setProps

### ISSUE THREAD

**Issue by jessedrelick** [mquan/cortex#66]
Hello and thanks for creating this library! Passing callbacks all the way down into child components to update root-level props is a pain, so I find the concept behind Cortex quite intriguing. However, I am confused about the following from the example: 

    orderCortex.on("update", function(updatedOrder) {
      orderComponent.setProps({order: updatedOrder});
    });

My understanding is the Cortex object we create and provide to the React component is used in place of properties, as it is in your example:

    var orderCortex = new Cortex(orderData);

    var orderComponent = React.renderComponent(
      <Order order={orderCortex} />, document.getElementById("order")
    );

Properties are never passed into the component, so why would we call setProps? Would forceUpdate() make more sense in order to re-render components based on the new values of the Cortex object? Perhaps I am missing something, but I thought Cortex replaces properties being passed into components.

Thanks,
-Jesse

**Comment by mquan** [comment]
Cortex object does not replace props. It is in fact passed as props into your React component. Cortex is simply a wrapper for your data. It is better to call setProps because it specify the updated props. 

The way cortex works is it only allows update at the props of the root component. When a child component updates its data cortex issue an event up the chain to change data only at the root. Please check out the README for more info

**Comment by jessedrelick** [comment]
Thanks for your fast response. The part I'm still confused on is we are passing the Cortex-wrapped properties into the component, not this.props so why do we need to update props if they aren't used? We should only need the Cortex-wrapped properties.

### STANDARD METHOD

    var App = React.createClass({
      getDefaultProps: function () {
        return {
          key: "value"
        }
      },
      update: function (obj) {
        this.setProps(obj);
      },
      render: function () {
        return (<SomeComponent {...this.props} update={this.update} />)
      }
    });

### CORTEX METHOD
     var App = React.createClass({      
     cortexObject: new Cortex({key: value}); 
     // update function not needed because we can do this.props.key.set('newvalue') and  cortex object updates itself; only need to forceUpdate to cause re-render with new cortex values
      componentWillMount: function () {
         var self = this;
         this.cortexObject.on("update", function(updated) {
             // cortexObject is used in place of Props, so why update props if they aren't used? forceUpdate instead
             self.forceUpdate();
         });
      },
      render: function () {
        return (<SomeComponent {cortexObject} />)
      }
    });

Why I am confused is root-level props are never passed into components, only the Cortex Objects, so by updating the Cortex Object there should be no reason to setProps considering they aren't used, forceUpdate() can be used to re-render.

**Comment by mquan** [comment]
There's nowhere in cortex doc that specifies using cortex the way used in SomeComponent. In the quick example, orderCortex is the root cortex object and it's passed in as order props. Please review React doc on props if you're not familiar with how props work

**Comment by mquan** [comment]
Sorry, I was on mobile previous few days so could not make my point clearer.

```javascript
var orderCortex = new Cortex(orderData);

var orderComponent = React.renderComponent(
  <Order order={orderCortex} />, document.getElementById("order")
);
```

The part `order={orderCortex}` above is exactly how you pass cortex object as `this.props.order`

Cortex does not dictate how you use it along with React. These are the different ways I've seen cortex used along with React 
- pass it in as props and call `setProps` in cortex callback. This is the simplest and the recommended way.
- define it as state within a root component and have that component manage cortex. This is almost the same as the first approach, the only difference is the cortex object is defined from within a component and you call `setState` in cortex callback.
-

**Comment by jessedrelick** [comment]
Okay makes sense, I was just a little confused on the relationship between the Cortex Object and the component props. Thanks for clarifying and great job on the library!

**Comment by jimknight** [comment]
Quan, I'm using the second method of defining the cortex as state in the root component and it works great when defining in the getInitialState function. But I need to populate some of the cortex data with an ajax request and am doing the ajax call inside the componentDidMount function. So normally I would do a this.setState({something: ajaxResults}) but with the state defined as a cortex named "data", I'm not sure how to address it. Would I use "set"? It's not props, it's state so I'm not sure how to update the state when it's a cortex.

  getInitialState: function(){
    var cortex = new Cortex({
      title: "First Project",
      emails: [],
      projectId: "",
      emailSelectedId: 5,
      displayedEmail: {
        showDeleteButton: true,
        showNewTaskButton: true,
        showNewTaskForm: false,
        body: "content here", subject: "welcome"
      }
    });
    cortex.on('update', function(newData){
      this.setState({data:newData});
    }.bind(this));
    return {
      data: cortex
    };
  },

Under componentDidMount:

this.state.data.set({projectId: "4"}) 
OR
this.setState({data:{projectId:"4"}})
OR 
Something else? I guess what I'm asking is if you can point me to an example of someone using state at the root level vs the render method. I'm using react-router which is why I'm doing it this way.
Thanks

**Comment by mquan** [comment]
@jimknight your callback already call setState so you just need to call `this.state.data.set({projectId: "4"})` and when cortex completes its update it will invoke that call back.

**Comment by jimknight** [comment]
Thanks for your answer. Unfortunately, it doesn't seem to perform the update using this.state.data.set({projectId: "4"}). See my console

![image](https://cloud.githubusercontent.com/assets/248317/6743684/8a082412-ce73-11e4-8f5d-10eac1ea4f06.png)

**Comment by mquan** [comment]
Because the cortex you initialize in `componentDidMount` is a different object than the one you initialize in `getInitialState`. You should do

```javascript
componentDidMount: function() {
    $.ajax({
      url: "projects/" + this.getParams().projectId + "/emails.json",
      dataType: 'json',
      success: function(jsonResponse) {
        console.log(jsonResponse);
        if (this.isMounted()) {
          console.log("isMounted");
          
         this.state.data.set({
           emaisl: jsonResponse,
           // and anything that changed from getInitialState
         });
        }
      }.bind(this),
      error: function(xhr, status, err) {
        console.error("projects/" + this.getParams().projectId + "/emails.json", status, err.toString());
      }.bind(this)
    });
  }
```

**Comment by jimknight** [comment]
Thanks Quan that worked!
