### ISSUE TITLE
Document how arrays are handled?

### ISSUE THREAD

**Issue by unclecheese** [mquan/cortex#69]
I'm not sure if this is an issue or not, but when I try to run `set()` on an array, I get a cryptic error in `DataWrapper.__subValue()` (line 70) saying "Can't set property '2' of undefined".

My data structure:

```js
{ a: {}, b: [] }
```
I'm trying to run `myCortex.b.set(newArray)`

If I log out `this.__updates[i].path`, right before the error, I get something that doesn't look quite right:

`["b", 1, 2]`.

The fix is to run `remove()` on the array before running `set()`. Is this by design? If so, should we document it?

**Comment by mquan** [comment]
Can you show all your code. I'm able to do this

```javascript
var data = {a: {}, b: []};
var myCortex = new Cortex(data);
var newArray = [1];
myCortex.b.set(newArray);
```

**Comment by unclecheese** [comment]
Here's how you can replicate it:

```js
var c = new Cortex({a: {}, b: []});
c.b.set([{id: 123, title: 'test1'}, {id: 124, title: 'test2'}, {id: 127, title: 'test3'}, {id: 777, title: 'test4'}]);
```

**Comment by mquan** [comment]
This looks like a bug, I'm fixing it soon. In the meantime, you can get around the problem by using push

```javascript
var c = new Cortex({a: {}, b: []);
var myArray = [
  {id: 123, title: 'test1'}, 
  {id: 124, title: 'test2'}, 
  {id: 127, title: 'test3'}, 
  {id: 777, title: 'test4'}
];

for(var i = 0, ii = myArray.length; i < ii; i++) {
  c.b.push(myArray[i]);
}
```

There's no performance difference as everything is processed in an event loop

**Comment by mquan** [comment]
This is fixed, please reopen if you find any problem
