### ISSUE TITLE
How to tests the components with Cortex?

### ISSUE THREAD

**Issue by howtomakeaturn** [mquan/cortex#70]
Hi!
I've been using Cortex in my company for a while.
Recently I want to create tests for my React components.
But it's not easy since all the props are wrapped in Cortex.
Any ideas about how to do this?
Thanks!

**Comment by mquan** [comment]
Have you tried jest http://facebook.github.io/jest/docs/tutorial-react.html

**Comment by howtomakeaturn** [comment]
I see. I will give it a try. Thanks!
