### ISSUE TITLE
getChanges() on unshift() operations

### ISSUE THREAD

**Issue by unclecheese** [mquan/cortex#72]
Calling `unshift` results in every single property of every single item being flagged as changed, since all of the keys are now one increment off. This is, of course, the expected result.

Would there be a way to fine-tune this a bit so that Cortex is a bit smarter about these operations? In practice, I really only want to know that one change was made -- a new item at the beginning of the list.

Any thoughts?

**Comment by mquan** [comment]
I initially allow methods to build changes and pass them in as input but decided against it as it breaks the standard pattern. I'll be happy to spend some time reinvestigate this now that `getChanges` code becomes stable.
