### ISSUE TITLE
won't compile with browserify

### ISSUE THREAD

**Issue by mixtur** [mquan/cortex#73]
I have a project that uses browserify and cortexjs.

1. your source code apparently uses babelify.
2. my own project also uses babelify.
3. browserify will not apply transforms in node_modules unless you will explicitly told it to.

I currently solved the problem by adding to my `node_modules/cortexjs/package.json` string `"browserify":{"transform": ["babelify"]}`. Which is obviously bad, when done on my side. Can you please do it on yours?

**Comment by mquan** [comment]
The transformation is done in the gulpfile. It's been working fine since we switch. What do you mean by "compile". The build/cortex.js file is the compiler file, why do you need to compile anything?

**Comment by mixtur** [comment]
I mean Cortex inside of my project won't compile. Cortex by itself probably compiles just fine.

To reproduce problem we have to do this;
Create file `my_code.js`
```javascript
  import Cortex from 'cortexjs';
```
...then execute...
```bash
cd /path/to/my_code.js
npm install cortexjs babelify
browserify my_code.js -t babelify -o bundle.js
```

And we have plain "class DataWrapper..." in compiled code. Which of course will not work in browser.

But if we change `node_modules/cortexjs/package.json` like I said above, then everything is fine.

**Comment by mquan** [comment]
Ah I see, I will fix it by setting the main file to build/cortex.js

I think this makes more sense as how cortex transform its code should not be an external dependency

**Comment by mixtur** [comment]
Then probably there will be another problem. With "require" calls in your compiled code. 
Browserify will try to find correspondent modules, and will use them even though they are already compiled in bundle.

You can add [derequire](https://www.npmjs.com/package/gulp-derequire) step to build process to avoid that.

**Comment by mquan** [comment]
build/cortex.js is usable in the browser and doesn't have require

**Comment by mixtur** [comment]
https://github.com/mquan/cortex/blob/master/build/cortex.js#L11

Browserify just blindly searches for calls to functions named "require", without figuring out what that "require" actually means.
In this case it will try to find build/pubsub.js and will fail of course.

To test it I tried the same "my_code.js", and modified field "main" in "node_modules/cortexjs/package.json" as you suggested. Yes it fails.
