### ISSUE TITLE
Consolidate multiple changes for the same subtree

### ISSUE THREAD

**Issue by mquan** [mquan/cortex#74]
These following cases yield double changes where as there should be no change:
- set a value to something and set it back.
- insert an element at the beginning of an array, then remove one next to it. No change should be shown for subsequent elements but there are 2 changes for each.

Changes should be merge and reflect the final state

**Comment by mquan** [comment]
A better approach is to consolidate updates upfront before performing them so we don't even have multiple changes for the same node.

**Comment by RangerMauve** [comment]
Is what you're suggesting basically "batch updating"?

It might look like:

``` javascript
var batch = value.batch();
batch.set("foo", bar);
batch.set("baz", "fizz");
batch.exec();
```

**Comment by mquan** [comment]
We already have batch update. This is to merge updates on the same node so it doesn't produce 2 multiple changes.
