### ISSUE TITLE
Copy State and Diff?

### ISSUE THREAD

**Issue by nickretallack** [mquan/cortex#76]
I noticed Cortex can tell you what changed since the last update cycle.  This is cool and all, but what I really want to do is find out what changed since the last time I saved data to the server.

Here's how it'd work.  When you start editing a record in your browser, I'd like to copy the relevant cortex subtree to remember what it used to look like.  Then, when you hit Save, I'd like to diff the current state of the subtree with the saved copy, getting something much like the result of `getChanges()`.  Now I know what to send to the server to get things in sync!

----

Btw I want to say I just started using Cortex and I love it!  Calling mutators on Cortex is way less work than writing a bunch of action handlers for a Flux app.  It even fixes "the dot rule" problem in Angular apps where you can only really mutate a value if you have access to its parent object.  Working with Cortex actually feels a lot like working with FireBase.  In fact, I think Cortex's API is better than FireBase's, and it'd be cool if there was a cortex-firebase library that let you use FireBase via Cortex.  But that's for a different issue, and may be a silly idea.  Cortex also feels kind of like using mutable "reference" values in oCaml, since you can assign them in place without knowing about other places they are referenced.  And it seems very similar to Functional Reactive Programming stuff like ELM, only you don't have to write any actions.

**Comment by mquan** [comment]
Thanks for the idea. You can already do clone and diff using __clone and __diff at any data level. I can refactor them into utility methods when I have time

**Comment by nickretallack** [comment]
I just realized I could cheese this like so:

```
function copyState(cortex) {
	return JSON.parse(JSON.stringify(cortex.getValue()))
}

function getChanges(cortex, initial_value) {
	new_value = cortex.getValue()
	cortex.set(initial_value)
	setTimeout(function(){
		cortex.set(new_value)
		changes = cortex.getChanges();
		console.log(changes)
	})	
}

// save state
var saved_state = copyState(cortex)
// ... change things
var changes = getChanges(cortex, saved_state)

**Comment by mquan** [comment]
you can now call `Cortex.deepClone` and `Cortex.deepDiff`. Please refer to readme doc for more info. Thanks

**Comment by nickretallack** [comment]
Thanks!

**Comment by unclecheese** [comment]
@nickretallack I'd really like to implement something like what you're describing. Do you have any code you can share demonstrating how you negotiate what needs to be sent to the server based on the diff?
