### ISSUE TITLE
Use with React Native

### ISSUE THREAD

**Issue by iceNuts** [mquan/cortex#78]
Hi there,

I use cortex in React Native, it works and there is a callback, however, I can't setState in the callback function as I use createClass which only grants me a descriptor. So where can I get an instance able to call setState because it is react native, the elements are very different, I don't think I could use the way in your example code (can't use renderComponent to gain instance..). 

Thanks.

**Comment by mquan** [comment]
Can't you get a handle of your root component like this?

```javascript
var myRootComponent = AppRegistry.registerComponent('MyRootComponent', () => MyRootComponent);
```

**Comment by iceNuts** [comment]
yeah, I can get the root component, but how can I modify its child component's state?

**Comment by mquan** [comment]
Then you pass cortex in as props and pass it down to your child component as prop. Please follow the README example if you have anymore question

**Comment by iceNuts** [comment]
Yes, this is what I did. My main concern is to use the upstream data in cortex callback outside the components to update UI.

**Comment by mquan** [comment]
The example in the README also `setProps` outside of the component, what's wrong with that?

**Comment by iceNuts** [comment]
Example works well but for my code, I use NavigatorIOS in root component to route, then I don't have a way to get router's child component and set its state when callback is called which is outside, so I can't use refs.

**Comment by mquan** [comment]
Do you have code sample?

**Comment by iceNuts** [comment]
Sure,

This is render function in root:
```
render: function() {
    return (
      <TabBarIOS>
        <TabBarIOS.Item 
          title='Upload' 
          selected={this.state.selectedTab === 'AddItemTab'}
          onPress={() => {
            this.setState({
              selectedTab: 'AddItemTab',
            });
          }}>
          <Router
            firstRoute={AddItemRoute}
            backButtonComponent={BackButton}
          />
        </TabBarIOS.Item>
        <TabBarIOS.Item 
          title='Delivery'
          selected={this.state.selectedTab === 'DeliverItemTab'}
          onPress={() => {
            this.setState({
              selectedTab: 'DeliverItemTab',
            });
          }}>
          <Router 
            firstRoute={{
              name: '发货',
              component: DeliverItemView
            }}
            backButtonComponent={BackButton}
          />
        </TabBarIOS.Item>
      </TabBarIOS>
    );
```
My cortex outside:
```
// cortext callbacks
formCortex.on("update", function() {
  console.log(rootComponent.refs);
  var brand = formCortex.brand.getValue();
});
```

**Comment by mquan** [comment]
What component is that render function? and where is the formCortex defined?

**Comment by iceNuts** [comment]
This is defined outside from components:
```
// upstream data
var formData = {brand: {}, category: {}, sizeChart: {}};
var formCortex = new Cortex(formData);
```
The render function is for root component, aka, component get from AppRegistry:

```
var rootComponent = AppRegistry.registerComponent('Client', () => Client);
```

**Comment by mquan** [comment]
And where's the Client component?

**Comment by iceNuts** [comment]
All of them are in the same file.

**Comment by iceNuts** [comment]
Router is react-native-router, I am an iOS developer and very new in React, thanks for the great help.

**Comment by mquan** [comment]
so you can use `getDefaultProps` to pass formCortex in as your props or use `rootComponent.setProps`. Then just pass the cortex object into child components under Client `component`. Callback should be

```javascript
formCortex.on("update", function(updatedCortex) {
  rootComponent.setProps(....)
});
```

**Comment by iceNuts** [comment]
```
rootComponent.setProps(....)
```
This causes an error, undefined is not a function. I think it is because of rootComponent?

**Comment by mquan** [comment]
well you have to make sure rootComponent is a React Native component. Because what AppRegistry.registerComponent return may not be. If not you can always initialize it in `getInitialState`

```javascript
getInitialState: function() {
  var formCortex = new Cortex(formData);
  formCortex.on("update", function(updatedCortex) {
    this.setState({cortex: updatedCortex});
  });
  return { cortex: formCortex };
}
```

**Comment by iceNuts** [comment]
Thanks mquan, but the ```this``` is also undefined. I am really curious about the context in callback function.

**Comment by mquan** [comment]
do this

```javascript
getInitialState: function() {
  var formCortex = new Cortex(formData);
  var self = this;
  formCortex.on("update", function(updatedCortex) {
    self.setState({cortex: updatedCortex});
  });
  return { cortex: formCortex };
}
```

**Comment by iceNuts** [comment]
It finally works! Great! Thank you very much mquan. Can you please explain why ```this``` here is ```undefined```? Is it in cortex context?

**Comment by mquan** [comment]
You should read up on `this` in javascript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

**Comment by RangerMauve** [comment]
@iceNuts Because callbacks normally lose the value of `this` when they get passed around. To ensure that `this` gets preserved in the callback, either use [.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) or [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

**Comment by iceNuts** [comment]
@mquan @RangerMauve thank you guys. let me dig it deeper.
