### ISSUE TITLE
pre-built warning with webpack

### ISSUE THREAD

**Issue by manveru** [mquan/cortex#79]
I'm using cortex alongside webpack, and apparently it's not too happy about the way cortex.js looks like. I tried googling for a while, but couldn't find any suggestions on how to fix this.

    WARNING in /home/manveru/~/cortexjs/build/cortex.js
    Critical dependencies:
    1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ /home/manveru/~/cortexjs/build/cortex.js 1:479-486

**Comment by manveru** [comment]
I tried building it myself without browserify and using `gulp-babel` instead. Stumbled upon this issue:

    SyntaxError: /home/manveru/project/node_modules/cortexjs/src/cortex.js: Line 8: 'this' is not allowed before super()

It's caused by https://github.com/babel/babel/issues/1131 and should probably be fixed in cortex. I'll whip up a PR to fix the syntax error, but maybe also updating babelify to 6.0.2 might be a good idea for this project anyway.

**Comment by mquan** [comment]
Thanks I'll update babelify

**Comment by mquan** [comment]
babelify updated to 6.1.1
