### ISSUE TITLE
Sorting array does not trigger update

### ISSUE THREAD

**Issue by unclecheese** [mquan/cortex#83]
Here's a test you can run:

```js
Cortex.on('update', function(data) {
	console.log('there was an update');
});

console.log('initial set');
Cortex.currentFolder.set({
	folder: {},
	children: ['c', 'b', 'a']
});
setTimeout(function () {
  // This shows 'c','b','a', as expected
  console.log('initial children', Cortex.currentFolder.children.getValue());
  var o = Cortex.currentFolder.getValue();
  console.log(o); // children are sorted, 'a','b','c' at this point
  o.children.sort(); // But the sort doesn't happen until here

  // Both arrays are sorted 'a','b','c' here
  console.log('sorted', o.children, Cortex.currentFolder.children.getValue());

  // Therefore, this does not generate a diff, and there's no update
  Cortex.currentFolder.set(o);
}, 0);
```

**Comment by unclecheese** [comment]
I can also produce the same behaviour using `push()` to the array in lieu of `sort()`. Any mutation to the array affects the DataWrapper. Have tested using `object-assign` to create a clone, and that makes no difference.

**Comment by unclecheese** [comment]
Update: Just saw your recent commit that exposes the `deepClone` method, and it got me wondering.

This works as expected:

```js
myCortex.on('update', function(data) {
	console.log('there was an update');
});

myCortex.currentFolder.set({
	folder: {},
	children: ['c', 'b', 'a']
});
setTimeout(function () {
  var o = Cortex.deepClone(myCortex.currentFolder.getValue());
  o.children.sort();
  myCortex.currentFolder.set(o);
}, 0);
```

Is this intentional? And if so, I'm wondering if `deepClone` needs to be a instance method of `DataWrapper`, so I could just do:

```js
var o = myCortex.currentFolder.deepClone();
```

Seems a bit more natural to me.

**Comment by mquan** [comment]
This is a good idea, but I'm not sure it's clear that it's deep cloning the value and not the wrapper. To make that clearer we need to call it something like deepCloneValue or valueClone

**Comment by unclecheese** [comment]
True. Did you have any thoughts on the main issue? It's kind of weird that `deepClone()` is even necessary in this case, no?

**Comment by mquan** [comment]
Can you check the value after you set `Cortex.currentFolder.set(o);` I think it's the right value, the reason it's not calling update is because the value already changed when you sort `o.children.sort();` It's unfortunate that we're working with a single copy of the value. You can fix this by either 1) cloning the value before sort or 2) sort without mutating the source array.

It would be ideal if cortex can somehow detect and prevent value mutation that's not using `set`.

**Comment by unclecheese** [comment]
Great, that's what I thought. Having `deepClone()` exposed publicly has helped immeasurably.
