### ISSUE TITLE
Bitten by using cortex + component state not carefully: item.val().field != item.field.val()

### ISSUE THREAD

**Issue by bulatshafigullin** [mquan/cortex#84]
Hi,
I'm using  cortex in my website for admin panel, nothing really huge, but I've got a REALLY annoying bug fixed recently.
So I'm using cortex for managing one big global data bundle and I have tabs in the app. When user clicks a tab, I make it active by putting some data into that tabs local state, and making updates throw cortex set method to the data in the tab. At the beginning it worked good. But at some point I've  messed up with updates and rerendering somehow. What I've got is that if I call `this.props.item.val().is_active` it says `true`, and when I call `this.props.is_active.val()` it says `false` after 2 changes made, i.e. it works for the first time, and doesn't for the second time. And it rerenders component at the first time, and not renders at the second time.
So my point is, if you see some kind of weird things like this, my advice is to check your code for places where you put some cortex wrapped data into local state. It seems to me in my app local state updates somehow interfered with cortex updates.

**Comment by mquan** [comment]
Thanks for reporting the issue but without knowing much about how you're using it I'm not sure how to debug it. Specifically I definitely expect these two to be different objects and their values must be independent: `this.props.item.val().is_active` and `this.props.is_active.val()`. Do you mean `this.props.item.is_active.val()` for the second one?

You don't have to show me all your code, just boil it down to the simplest case that replicate your problem and set it up on jsbin or jsfiddle.

**Comment by bulatshafigullin** [comment]
Yes, I mean this.props.item.is_active.val()

>> You don't have to show me all your code, just boil it down to the simplest case that replicates your problem and set it up on jsbin or jsfiddle.
I'm working on this, will post a link here soon.

**Comment by mquan** [comment]
@bulatshafigullin any update on how to reproduce the problem?

**Comment by mquan** [comment]
Please reopen once you have a concrete example
