### ISSUE TITLE
Using set() with objects

### ISSUE THREAD

**Issue by hnordt** [mquan/cortex#85]
Hello.

I started to use Cortex today. It's amazing!

I have one question, set() doesn't work with objects?

Here is what I've tried:

```javascript
var Cortex = require('cortexjs');

var data = { a: { b: 2 } };

var cortex = new Cortex(data);

cortex.a.set({
    c: 3
});

console.log(cortex.a.getValue()); // output: { b: 2 }, expected: { c: 3 }
```

Am I doing something wrong?

**Comment by mquan** [comment]
The reason is changes are updated in batch at the end of the run loop. The best place to read updated data is inside the callback

**Comment by hnordt** [comment]
My mistake, sorry!

Thank you.
