### ISSUE TITLE
after removeAt() React is not picking up that the array has changed 

### ISSUE THREAD

**Issue by serle** [mquan/cortex#87]
After  calling removeAt() React is not picking up that the array has changed, neither is calling didChange() on the Array key.

**Comment by mquan** [comment]
I'm able to get the correct changes by running the following code

```javascript
var myData = {a: [1, 2, 3]};
// > undefined
var cortex = new Cortex(myData);
// > undefined
cortex.a.removeAt(0)
// > [1]
cortex.a.didChange()
// > true
cortex.a.getChanges()
// > [ObjectnewValue: 2oldValue: 1path: Array[1]type: "update"__proto__: Object, ObjectnewValue: 3oldValue: 2path: Array[1]type: "update"__proto__: Object, ObjectnewValue: undefinedoldValue: 3path: Array[1]type: "delete"__proto__: Object]
```

Can you show  code to reproduce it?

**Comment by serle** [comment]
Hi,

I have tried both removeAt(0) and removeAt(1) and didChange() returns false. I am receiving the inChange event. I subsequently try to do a React.render and it also seems to think that nothing has changes as its not re-rendering.

var myData = {a: [1, 2, 3, 4, 5]};
var cortex = new Cortex(myData);
cortex.a.removeAt(1);
cortex.a.didChange();
>false

Thanks for the Help

**Comment by mquan** [comment]
The issue is cortex only update at the end of the event loop so you have to check for change in the callback.

```javascript
var myData = { a: [1, 2, 3]};
var cortex = new Cortex(myData, function(updatedCortex) {
  // you must check for change here
  console.log(updatedCortex.a.didChange();
});

cortex.a.removeAt(0);
```
