### ISSUE TITLE
Using setProps to do the react update is depricated, per cortex intro

### ISSUE THREAD

**Issue by serle** [mquan/cortex#88]
Note I found the only way to get cortex to initiate a proper re-render of a top-level es6 React component, using the suggested render({model: cortexdata}) is as follows:
  
 model.on("update", function(updated_model) {
        print_changes(updated_model);
        react_cmp.render({model: updated_model});
        react_cmp.forceUpdate();
    }.bind(this));

Note the forceUpdate() is essential to get react to initiated the re-render calculations properly at the top-level. Thereafter React seems to only render components if the cortex subtree contains changes. So forceUpdate() is not actually forcing and update. This may be a react issue but it would help to change the cortex intro document to reflect this.

**Comment by mquan** [comment]
I'm not aware of the convention of calling render method. I find this to be less efficient and possibly not correct to always rerender on cortex update than simply calling setProps. Can you point me to the react documentation that suggests this. Thanks

**Comment by mquan** [comment]
Nvm, I found the doc here https://facebook.github.io/react/docs/component-api.html#setprops

I don't think using `forceUpdate` is the solution here. I'll investigate why `render` does not pick up the updated cortex. May be it has some builtin comparison that does not recognize props changes because cortex isn't immutable.

**Comment by mquan** [comment]
In the meantime, you can follow the suggestion here https://github.com/facebook/react/issues/4087

Basically, you manage the state of top level component instead of using props.

**Comment by mquan** [comment]
I added the following to the README, let me know if you have any question

```javascript
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    // Assume you pass your data into props as myData
    var myCortex = new Cortex(props.myData, (updatedCortex) => {
      this.setState({myCortex: updatedCortex});
    });

    this.state = {myCortex: myCortex};
  }

  render() {
    // access cortex data from this.state.myCortex
  }
}
```
