### ISSUE TITLE
Please publish v2.0.2

### ISSUE THREAD

**Issue by serle** [mquan/cortex#98]

**Comment by mquan** [comment]
It's already published https://www.npmjs.com/package/cortexjs

**Comment by serle** [comment]
Hi Quan,I don't understand the reason, but bower only picks up three versions the last version that bower picks up for cortex is 1.8.7 although the content of the git site has 2.0.2. I have removed cortex as a bower managed dependency, in the meantime, to stop bower reverting the library back to the older version.Regards,Serle ----- Original Message ----- From: Quan Nguyen [mailto:notifications@github.com] To: cortex@noreply.github.com Cc: serle@infoworker.co.za Sent: Thu, 08 Oct 2015 09:33:43 -0700 Subject: 
Closed #98.

**Comment by mquan** [comment]
Hmm that's weird, because there's never a version 1.8.7, may be you meant 0.8.7? I think bower suppose to pick up a new release as soon as the bower.json version changes, but it didn't. You may want to use npm or simply copy the source then.

**Comment by serle** [comment]
Yip, you are right it seems stuck on 0.8.7. Bower only reports three versions. I think GitHub also has only 3 "releases", if you look at the releases tab, so I assume bower is somehow using the GitHub releases instead of the bower.json file. I worked around it for now by copying the source and deleting it from my bower dependencies to stop it overwriting the 2.0.2 source with 0.8.7. I had done the conversion, then bower intervened when I tried to install another library and overwrote 2.0.2. At some point I'd like to put the dependency back.----- Original Message ----- From: Quan Nguyen [mailto:notifications@github.com] To: cortex@noreply.github.com Cc: serle@infoworker.co.za Sent: Fri, 09 Oct 2015 09:06:19 -0700 Subject: 
Hmm that's weird, because there's never a version 1.8.7, may be you meant 0.8.7? I think bower suppose to pick up a new release as soon as the bower.json version changes, but it didn't. You may want to use npm or simply copy the source then.

**Comment by mquan** [comment]
I just made another release, please verify 2.0.2 is available on bower

**Comment by serle** [comment]
Thanks,Yes the problem is resolved now :)Regards,Serle----- Original Message ----- From: Quan Nguyen [mailto:notifications@github.com] To: cortex@noreply.github.com Cc: serle@infoworker.co.za Sent: Sat, 10 Oct 2015 08:38:48 -0700 Subject: 
I just made another release, please verify 2.0.2 is available on bower
